language: java
git:
  depth: 9999
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    sudo: required
    services:
      - docker
    before_deploy: 
      - git config --local user.name "Open Identity Platform Community" && git config --local user.email "open-identity-platform-openidm@googlegroups.com"
      - git checkout -f $TRAVIS_BRANCH
      - git tag -f $git_version && git tag -d $git_version
      - mvn -q -B -DreleaseVersion="$git_version" -DtagNameFormat="@{project.version}" -DignoreSnapshots=true  -DpushChanges=false -DscmCommentPrefix="[ci skip] $TRAVIS_REPO_SLUG " -DskipTests -Darguments=-DskipTests -Dresume=false clean release:prepare 
      - git push --quiet --force https://$GITHUBKEY@github.com/$TRAVIS_REPO_SLUG.git >/dev/null 2>&1
      - git push --quiet --force https://$GITHUBKEY@github.com/$TRAVIS_REPO_SLUG.git $git_version >/dev/null 2>&1
    deploy:
      provider: releases
      draft: false
      prerelease: false
      target_commitish: $(git rev-list -n 1 $git_version)
      tag_name: $git_version
      name: $git_version
      body: "compare: $(git rev-list -n 1 $git_version_last)...$(git rev-list -n 1 $git_version)"
      api_key:
        secure: q4TZ19/xIc+mjDTxkjnqfJk2Yv9NXnLLtnHfydRMSSOT2lIDd73lzIAKkC/x4dqEYGPpM57XGYq1qPpMVQqyUjnIkOoyUwZd/+iLf+Aox6uNzhHaTYm9dIZbQAa40q945S+fjkzG4ZptO2jS6KoddcWLSCO2yXulMHiV+R3KYTau1NzZX9YkSdloMLiFUs9OjjmyR+VJVw8iuWW2YD3Wrv5vXYlmvhMO54h1nVwiWnWXctuFkW5KDQ6ERfFUwk58hz2UNRqrwaXlN9pCCkp30DkOfGIllQgJvb256ILJoRlqFNF7k2yXLr2dVvURnE3ZOYJPGSEjzFx5+lfyRimx8lmCqDIcOR971HkZocMhCCrneyfPa7L9s8b6E9seEdVdPnPJxhyH2RaFoeoD0I4ZhtZcNSkwV4+YLyLVUrTj7otGfXaGGGmCMZNN0cS3TDhpVUzHpoZnbhsb7cwr6HFzuMV5l2YxeB7vTaidE3wQif4ptTGU3aoenPVvO4NFHwxNMH9kJIUcRdXBQ6uem5fxfHgBVBBJ+4z86/2nJtlRKa8EDXoy5IqBoX8l/Xsiyom/hhjawaZDTHP8hKE2EcBQ/0v5UkQnrFKL//XqKm7buODUCWvDRSpDN3zzi6w+tFOl+Wqnq/OHKGF5+PPjY9Yg1maxeDlvHc52F08i7xVA/Y4=
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file: 
        - "OpenICF-java-framework/openicf-zip/target/*.zip"
        - "OpenICF-csvfile-connector/target/*.jar"
        - "OpenICF-databasetable-connector/target/*.jar"
        - "OpenICF-groovy-connector/target/*.jar"
        - "OpenICF-kerberos-connector/target/*.jar"
        - "OpenICF-ldap-connector/target/*.jar"
        - "OpenICF-ssh-connector/target/*.jar"
        - "OpenICF-xml-connector/target/*.jar"
      on:
        repo: OpenIdentityPlatform/OpenICF
        tags: false
        branch: 
          - master
          - travis
    after_deploy:
      - echo 'after_deploy'
      - echo 'build and push Docker'
      -   #docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      -   #docker build ./openicf-distribution/target -t $DOCKER_USERNAME/openicf -t $DOCKER_USERNAME/openicf:$git_version
      -   #docker push $DOCKER_USERNAME/openicf:$git_version
      -   #docker push $DOCKER_USERNAME/openicf
  - os: linux
    jdk: openjdk8
  - os: osx
    osx_image: xcode9.1
  allow_failures:
  - os: osx
  - jdk: openjdk8
branches:
  except:
    - /[0-9]+\.[0-9]+\.[0-9]+$/
notifications:
  email:
  - open-identity-platform-openicf@googlegroups.com
before_install:
  - date -u
  - uname -a
  - # if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew install rpm wine; else sudo apt-get install -y rpm wine; fi 
  - git fetch -t
  - export git_version_last="$(git describe --abbrev=0 --tags --always)"
  - export git_version="$(echo $git_version_last | awk -F . '{ printf "%d.%d.%d", $1,$2,$3 + 1}')"
  - env | sort
  - git log `git describe --tags --abbrev=0 HEAD^ --always`..HEAD --oneline 
install:
  - mvn -q -B -DskipTests -Dmaven.javadoc.skip=true install -f OpenDJ/forgerock-parent
  - mvn -q -B -DskipTests -Dmaven.javadoc.skip=true install -f OpenDJ -P\!distribution
script:
  - bash -c "while true; do tail -256 build.log; sleep 60; done" &
  - PING_LOOP_PID=$!
  - mvn -B clean install >> build.log 2>&1
  - kill $PING_LOOP_PID
  - tail -1024 build.log
  - #mvn -B clean install
after_failure:
  - tail -8192 build.log